[package]
name = "mercury-protocol"
version = "0.1.0"
authors = ["Justin LeFebvre <jstnlefebvre@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3"
bytes = "0.4"
crc = "1.8"
lazy_static = "1.2"
log = "0.4"
